apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: argocd
  name: product-service
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret
      containers:
        - name: product-service
          image: ghcr.io/beowolf23/product-service:latest
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: product-service-config
            - secretRef:
                name: product-service-secret