server:
  http_listen_port: 3200

distributor:
  receivers:
    otlp:
      protocols:
        http:
          endpoint: "0.0.0.0:4318"  # Add HTTP endpoint
        grpc:
          endpoint: "0.0.0.0:4317"  # Add gRPC endpoint
storage:
  trace:
    backend: local
    local:
      path: /tmp/tempo/traces