include:
  - compose-kong.yaml
  - compose-observability.yaml
  - compose-kafka.yaml

services:
  inventory:
    container_name: "inventory-service"
    image: "inventory-service"
    environment:
      BPL_DEBUG_ENABLED: "true"
      BPL_DEBUG_PORT: "5005"
      BPL_DEBUG_SUSPEND: "false"
    ports:
      - "8081:8081"
      - "5006:5005" # used for remote debugging
    networks:
      - default
      - loki

  products:
    container_name: "product-service"
    image: "product-service"
    environment:
      BPL_DEBUG_ENABLED: "true"
      BPL_DEBUG_PORT: "5005"
      BPL_DEBUG_SUSPEND: "false"
    env_file:
      - product-service/.env.local
    ports:
      - "8080:8080"
      - "5005:5005" # used for remote debugging
    networks:
      - default
      - loki

networks:
  loki:
    driver: bridge
    external: false
  default:
    external: false
