server:
  port: 8080
spring:
  application:
    name: inventory-service
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
    driver-class-name: ${DB_DRIVER}
  jpa:
    database-platform: ${DB_DIALECT}
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      mode: always

logging:
  level:
    io.opentelemetry: DEBUG

management:
  tracing:
    propagation:
      type: w3c
    sampling:
      probability: '1.0'
  otlp:
    tracing:
      endpoint: http://otel-collector:4318/v1/traces
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      access: unrestricted
otel:
  service:
    name: inventory-service