name: Run Java tests with Maven and build Docker image with Buildpacks

on:
  push:
    paths:
      - 'product-service/**'
  workflow_dispatch:

env:
  IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/product-service
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: temurin
        cache: maven
        
    - name: Run Maven tests
      working-directory: product-service
      run: mvn test

    - name: Install pack CLI
      run: |
        (curl -sSL "https://github.com/buildpacks/pack/releases/download/v0.38.1/pack-v0.38.1-linux.tgz" | sudo tar -C /usr/local/bin/ --no-same-owner -xzv pack)

    - name: Log in to Github Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract Maven version
      id: version
      working-directory: product-service
      run: |
        VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
        echo "version=$VERSION" >> $GITHUB_OUTPUT

    - name: Build and push image with Buildpacks
      working-directory: product-service
      run: |
        pack build $IMAGE_NAME:${{ steps.version.outputs.version }} \
          --builder paketobuildpacks/builder-jammy-base \
          --env BP_JVM_VERSION=21 \
          --publish

    - name: Update image tag in Gitops manifest
      working-directory: gitops/product-service/base
      run: |
        sed -i "s|image: $IMAGE_NAME:.*|image: $IMAGE_NAME:${{ steps.version.outputs.version }}|" deployment.yaml

    - name: Commit and push GitOps manifest update
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add gitops/product-service/deployment.yaml
        git commit -m "Update image to version ${{ steps.version.outputs.version }}"
        git push
